language: python
python:
  - "2.6"
  - "2.7"
# need to work out map problem see:
# https://travis-ci.org/mennis/compute/jobs/31848402
#  - "3.2"
#  - "3.3"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests